---
title: "Medical Statistics"
subtitle: "Important Probability Distributions"
author: 
  - name: "Boncho Ku, Ph.D. in Statistics"
    email: secondmoon@kiom.re.kr
    orcid: 0000-0001-5520-9782 
    affiliation: 
       - name: Korea Institute of Oriental Medicine (KIOM)
         adress: 대전광역시 유성구 유성대로 1672 
institute: "Korea Institute of Oriental Medicine"
format: 
  revealjs: 
    logo: assets/ci/UIBS/JPG/UST-UI-SUBSIG-KRV.jpg
    slide-number: true
    show-slide-number: all
    chalkboard: 
      buttons: true    
    multiplex: true
    theme: [simple, assets/quarto-style-example/monash.scss]
    controls: true
    width: 1280
    height: 1024
    css: [assets/quarto-style-example/syntax-highlight.css, assets/quarto-style-example/custom.css, assets/quarto-style-example/pacman.css]
    header-includes: |
      <link rel="stylesheet" href="/assets/fontawesome-free-6.2.0-web/css/font-awesome.min.css">
      <script defer src="/assets/fontawesome-free-6.2.0-web/js/all.min.js"></script>    
editor: visual
---

# Important Probability Distribution

```{r setup-library}
library(MASS)
library(reshape2)
library(plyr)
library(tidyverse)
library(lubridate)
library(readxl)
library(tidyselect)
library(tidystats)
library(glue)
library(here)
library(gt)
library(gtsummary)
library(kableExtra)
library(icons)

# xaringanExtra::use_tile_view()
# xaringanExtra::use_progress_bar(color = "#23373B", location = "bottom")
# xaringanExtra::use_scribble()
# xaringanExtra::use_panelset()
# xaringanExtra::style_panelset_tabs(foreground = "honeydew", background = "seagreen")

```

## Bernoulli Trial

### `r icons::fontawesome("bullseye", style = "solid")` Definition

> A random experiment in which there are only two possible outcomes

::: {.callout-tip appearance="minimal"}
**Example**

<ul>

<li>Tossing a coin: Head (H) or Tail (T)</li>

<li>Take an exam: Success (S) or Failure (F)</li>

<li>True (T) or False (F)</li>

</ul>
:::

Let $X:\{S,F\} \rightarrow \{0,1\}$, that is

$$X = \begin{cases}
1~~~~~\mathrm{if~the~outcome~is~S}\\
0~~~~~\mathrm{if~the~outcome~is~F}\\
\end{cases}$$

::: panel-tabset
### PMF

Let $p$ be the probability of success, then the p.m.f of $X$ is

$$
f_X(x) = p^x(1-p)^{1-x}, x = \{0, 1\}
$$

### Expectation

$$
E(X) = p, ~~ Var(X) = \sigma^2 = p(1-p)
$$
:::


## Binomial Distribution


The Binomial distribution has three defining properties:

::: callout-important
-   Bernoulli trials are conducted $n$ times
-   The trials are independent
-   The probability of success $p$ does not change between trials
:::

### `r icons::fontawesome("bullseye", style = "solid")` Definition

> If $X$ counts the number of successes in the $n$ independent trials, we say that $X$ has a binomial distribution with the p.m.f 

$$
P(X = x) = f_X(x) = \binom{n}{k} p^x (1-p)^{n-x}, x=\{0, 1, \ldots, n\}
$$



