---
title: "UST: Medical Statistics Lecture Note"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


## **Course Overview**

> This course provides an introduction to important topics in statistical concepts and reasoning 
essential to quantitative medical research. 
> This course is lectured by a total of three faculty:
>
>   - Week 1 to 9: **Dr. Boncho Ku**
>   - Week 10 to 16: **Dr. Mimi Ko**


## **Course Level**

Introductory to intermediate


## **Prerequisites**

None. However, we expect that students are familiar with basic statistics.


## **Weekly Topics** 


```{r, echo=FALSE, message=FALSE, warning=FALSE}
require(tidyverse)
require(kableExtra)

input <- ("Week 1 (2021.03.04): Introduction to statistics
Week 2 (2021.09.02): Summary of data
Week 3 (2021.09.09): Concept of probability
Week 4 (2021.09.16): Random variables and probability distribution
Week 5 (2021.09.23): Important probability distribution
Week 6 (2021.09.30): Sampling distribution and statistical inference
Week 7 (2021.10.07): Estimation and hypothesis testing (1)
Week 8 (2021.10.14): Estimation and hypothesis testing (2)
Week 9 (2021.10.21): Correlation and Regression
Week 10 (2021.10.28): Design of clinical studies
Week 11 (2021.10.28): Analysis of continuous data (1)
Week 12 (2021.10.28): Analysis of continuous data (2)
Week 13 (2021.10.28): Analysis of categorical data (1)
Week 14 (2021.10.28): Analysis of categorical data (2)
Week 15 (2021.10.28): Sample size calculation
Week 16 (2021.10.28): Final exam
"
)
course_desc <- read.table(textConnection(input), sep = ":", header = FALSE)
course_desc$V3 <- c(rep("Dr. Boncho Ku", each = 9), rep("Dr. Mimi Ko", each = 7))
names(course_desc) <- c("Week", "Description", "Lecturer")
kbl(course_desc, 
    booktabs = TRUE, 
    caption = "Course Schedule (Week 1 ~ Week 9)") %>% 
  kable_paper %>% 
  kable_styling(bootstrap_options = c("hover"))

```


<!-- ### Week 1: Introduction  -->

<!-- Introduction to statistics and overview the world of statistics.  -->

<!-- ### Week 2: Terminologies and descriptive statistics  -->

<!-- Important terminologies related to statistics will be introduced. Illustrate the descriptive statistics including mean, variance (standard deviation),  -->
<!-- median, and inter-quartile range.  -->



## **Materials**

1.	Study Design and Statistical Analysis : A Practical Guide for Clinicians.  Mitchell H. Katz. 2006. Cambridge University Press 
2.	Medical Statistics: A Guide to SPSS, Data Analysis and Critical Appraisal. Berlinda Barton and Jennifer Peat. 2nd Edition. 2014. WILEY Blackwell 
3.	Statistics: Concepts and Controversies. David S. Moore and Willian Notz. 10th Edition. 2020. W.H. Freeman 
4.	Introduction to Statistical Methodology. Derek L. Sonderegger and Robert Buscaglia. https://bookdown.org/dereksonderegger/570/ 


## **Note**

This page is for Dr. Ku's course material only. 




